#!/usr/bin/env python3
#
#  gen_app_icon.py - bake assets/icon.png into src/app_icon.h.
#
#  Copyright 2026 Saxon Herschel Nicholls
#  SPDX-License-Identifier: MIT
#  (The generated icon DATA is Basseterre LLC's - see assets/NOTICE.)
#
#  The viewer sets its own window/dock icon with no runtime file dependency and
#  no image-decoding library:
#    - the PNG bytes are embedded whole, for macOS (NSImage decodes them itself,
#      giving a crisp Retina dock icon from the 256px master);
#    - small pre-decoded RGBA buffers (32 and 48) are embedded for
#      glfwSetWindowIcon, which wants raw pixels and only ever feeds a taskbar.
#
#  Regenerate after changing the icon:  python3 gen_app_icon.py
#  Requires ImageMagick (`magick`) only at generation time, never at build time.

import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC_PNG = HERE / "icon.png"
OUT = HERE.parent / "src" / "app_icon.h"
RGBA_SIZES = (32, 48)


def rgba(size: int) -> bytes:
    # magick -> raw 8-bit RGBA, exactly size*size*4 bytes on stdout.
    out = subprocess.run(
        ["magick", str(SRC_PNG), "-resize", f"{size}x{size}!", "-depth", "8", "RGBA:-"],
        check=True, capture_output=True,
    ).stdout
    want = size * size * 4
    if len(out) != want:
        sys.exit(f"expected {want} bytes for {size}px RGBA, got {len(out)}")
    return out


def emit(name: str, data: bytes) -> str:
    lines = [f"static const unsigned char {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + "".join(f"{b}," for b in data[i:i + 16]))
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    png = SRC_PNG.read_bytes()
    parts = [
        "// Generated by assets/gen_app_icon.py - do not edit by hand.",
        "// The icon DATA below is Basseterre LLC's, all rights reserved, and is",
        "// NOT under this repository's MIT license - see viewer/imgui/assets/NOTICE.",
        "#pragma once",
        "",
        emit("superlog_icon_png", png),
        f"static const unsigned int superlog_icon_png_len = {len(png)};",
        "",
    ]
    for s in RGBA_SIZES:
        parts.append(emit(f"superlog_icon_rgba_{s}", rgba(s)))
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
